### PR TITLE
First Pass at Docker

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
This include a Dockerfile, a .dockerignore, and documentation.

It relies on #74 in order to build the styles without running nodemon.

I think this could still be made more elegant, and am open to suggestions.

This most likely should no be merged yet, but I think it is a good first step towards making it easier for other people to deploy

/cc @ednapiranha @isaacs

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
Proof in the pudding --> http://bbs.kni.sh/post/post!1420710992-65

**Comment by TheAlphaNerd** [comment]
As #74 is closed there is nothing stopping this from landing if we want to officially allow docker support. (Unless anyone has specific ideas about it)

/cc @ednapiranha @isaacs

**Comment by ednapiranha** [comment]
@jasonrhodes @imakewebthings are you familiar w/ this stuff to r?

**Comment by imakewebthings** [comment]
None experience with Docker.

**Comment by jasonrhodes** [comment]
Same zero percent, sorry folks.

**Pull request merged**
