### PR TITLE
Refactor db to a single module, folder, conf value

### LINKED ISSUE #67: Organize DBs
Right now, there's a separate DB for each service, defined in the service js file.

It'd be nice, especially for testing, to have a single top-level config to specify the DB folder, and then have all of the services just use that as the root for their individual DB files.

(Aside: suggest adding a "refactor" or "code structure" tag for architectury type things that don't directly impact user-facing features but do make it easier to contribute?)

### PR DESCRIPTION
**Pull request by isaacs**
The better to override in tests, and DRY up a bunch of duplicated code.

It feels like lib/db.js should be some kind of dedicated "manage
multiple levelDBs in a single folder" module or something, but there's a
lot of BBS-specific stuff in there.  I'm not level-savvy enough to
confidently predict what other users might want in such a module, so I'm
tempted to just leave it as-is for the next brave soul to figure out.

Configuring the location of the db root folder is super important,
though.  Now, you could very easily start the server with something like
`node index.js --db /var/db/bbs` (or env or local.json) and it'll put
all the levels in there.  For tests, this makes it easy to wipe the db's
out and not accidentally the non-test databases.

Fixes #67

### CODE REVIEW

**Comment by ednapiranha** [comment]
Looks like it needs a rebase?

**Comment by isaacs** [comment]
Yep, I'll rebase tonight.

**Comment by isaacs** [comment]
Rebased, happy to land if another committer can bless it.

**Comment by isaacs** [comment]
Travis-CI failure is only due to requiring Twilio creds.

**Comment by TheAlphaNerd** [comment]
I have not yet had time to do a sanity check out the code changes, but the test suite passes on my box

**Comment by isaacs** [comment]
@spinda Hey, do you mind looking this over?  You'd had a PR a while ago that did a somewhat similar cleanup.

**Comment by jasonrhodes** [comment]
This all *looks* good but my tests keep failing on this IO Error I've been seeing in various places, intermittently:

```
$ npm test

> bigboringsystem@1.0.0 test /Users/jrhodes/personal/bigboringsystem
> lab


events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: IO error: ./test/db/profile/LOCK: No such file or directory
    at /Users/jrhodes/personal/bigboringsystem/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:114:34
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by isaacs** [comment]
@jasonrhodes Yeah, I just saw that, and fixed with a force-push to my db-factor branch.  Mind re-trying?

The issue is that the `resetDB` function needs to *not* be called while the app is doing stuff, or after it's been loaded, or else level has a fit.

**Comment by isaacs** [comment]
First ever green from Travis-CI, btw :100: ^

**Comment by jasonrhodes** [comment]
^5 on that sweet sweet Travis green...

Re-ran tests with those changes and all tests pass, LGTM!

**Pull request merged**
