### PR TITLE
updating deps for #182

### PR DESCRIPTION
**Pull request by coleGillespie**

### CODE REVIEW

**Comment by isaacs** [comment]
Causes a bunch of lint errors.  Not sure why just updating deps would do that.  Care to fix?

**Comment by imakewebthings** [comment]
I imagine that since one of the deps being updated is `eslint`, a new lint rule was added or default changed (`no-shadow`). You'll want to adjust our rc to allow the shadowing.

**Comment by coleGillespie** [comment]
Do we fix this by allowing shadowing in the rc rules or do we fix it by removing the shadows?

**Comment by isaacs** [comment]
I think var shadowing is a perfectly reasonable thing.  Please just update the rc rules to continue allowing it.  Much smaller diff, also.

**Comment by coleGillespie** [comment]
@isaacs done

**Comment by imakewebthings** [comment]
@coleGillespie Would you mind rebasing this off master again for a clean merge? My addition of `hapi-cache-buster` in the last couple days is mucking things up.

**Comment by coleGillespie** [comment]
looks like i had some issue in this rebase @isaacs maybe i should close this one and retry

**Comment by jasonrhodes** [comment]
The commit itself got a bit fucked up e4fe36ccca121046f9b719d466530b6aeb1f9fd9

It's got the Docker merge saved, honestly it's probably easier to just kill this PR, branch off master again, and resubmit unless you know an easy way to detangle! :)

**Pull request closed without merging**
