### PR TITLE
Clean up, refactor, fix bugs in lib/posts.js (and extend the pagination system)

### PR DESCRIPTION
**Pull request by spinda**
This started as an attempt to add a "newer" button to the posts pagination and ended up as a refactor/clean up of the code in `lib/posts.js` and the bits connected to it.

 - Multiple implementations of post streaming and pagination were merged into one.
 - Fixed a bug where deleting an account would delete all posts that shared a creation time with any of the users' posts, rather than just the users' posts. Eliminated unnecessary DB queries in this operation&mdash;previously this was doing one DB query per post to look up `post!` keys for each post, which didn't need to happen as the `post!` key can be derived from the `user~` key.
 - Renamed functions in `lib/posts.js` to better match what they do.
 - Saved a DB query when viewing the first page of "older" posts.
 - Added support for retrieving posts before another post in addition to posts after a post (`?first` to match `?last`). No UI is implemented for this here, though it is in [`newer-pagination-button`](https://github.com/spinda/bigboringsystem/tree/newer-pagination-button).
 - Fixed tests so they run without `resetDB` breaking them.
 - General code cleanup/fixing.

### CODE REVIEW

**Comment by isaacs** [comment]
Hey, @spinda, looks like this needs a rebase onto latest master.

Also, would it be possible to separate out the functional changes from any changes that are strictly refactoring/stylistic?  This is a pretty big diff, and I see that it fixes a gnarly bug, so I really want to land it, but I'd also like to make sure I'm reviewing the right things.

**Comment by isaacs** [comment]
Also, the changes to the DB handling tests might be better put off for now, since I'm already working in that area in https://github.com/bigboringsystem/bigboringsystem/pull/82.

**Comment by spinda** [comment]
I'll separate out the bugfix and resubmit.

**Comment by isaacs** [comment]
Oh, also, I think the bug might've been fixed by the addition of unique hex bits onto the end of the `post!...` ids.  The code still calls it "time", but that's just confusing, not broken.

**Pull request closed without merging**
